# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mentawai.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Nama')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Kiri'), (2, b'Kanan'), (3, b'Kiri dan Kanan')], verbose_name=b'Tipe')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('address', models.TextField(blank=True, null=True, verbose_name=b'Alamat')),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=mentawai.core.utils.FilenameGenerator(prefix=b'wave-photo'))),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='locations.Location')),
            ],
        ),
    ]
