# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=b'aktif'),
        ),
    ]
