# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('photos', models.ManyToManyField(related_name='contents', to='photos.Photo')),
            ],
        ),
    ]
