# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import mentawai.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Nama')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Kapal Feri'), (2, b'Pesawat')], verbose_name=b'Tipe')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, b'Senin'), (1, b'Selasa'), (2, b'Rabu'), (3, b'Kamis'), (4, b'Jumat'), (5, b'Sabtu'), (6, b'Minggu')])),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=mentawai.core.utils.FilenameGenerator(prefix=b'transportation-photo'))),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name=b'Waktu Keberangkatan')),
                ('arrived_time', models.TimeField(blank=True, null=True, verbose_name=b'Waktu Tiba')),
                ('pickup_location', models.CharField(max_length=50, verbose_name=b'Asal')),
                ('destination', models.CharField(max_length=50, verbose_name=b'Tujuan')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'aktif')),
            ],
        ),
    ]
