# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Kapal Feri'), (2, b'Pesawat'), (3, b'Kapal Antar Pulau')], verbose_name=b'Tipe'),
        ),
    ]
