# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'New'), (2, b'Completed'), (3, b'Failed')], default=1)),
                ('value', models.FloatField()),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('payment_id', models.CharField(default=b'', max_length=255)),
                ('error_log', models.TextField(blank=True, default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
