# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_histories', '0002_auto_20170506_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='number_of_visits',
            field=models.PositiveSmallIntegerField(default=15, verbose_name=b'Lama Kunjungan'),
        ),
    ]
