# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import mentawai.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Nama')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Description')),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=mentawai.core.utils.FilenameGenerator(prefix=b'partner-photo'))),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Website')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'aktif')),
            ],
        ),
    ]
