# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Penginapan'), (2, b'Rumah Makan')], verbose_name=b'Tipe'),
            preserve_default=False,
        ),
    ]
