# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-20 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_resort_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Resort'), (2, b'Penginapan')], verbose_name=b'Tipe'),
        ),
    ]
