# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import mentawai.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'Judul')),
                ('content', models.TextField(blank=True, null=True, verbose_name=b'Isi Berita')),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=mentawai.core.utils.FilenameGenerator(prefix=b'news-photo'))),
                ('is_active', models.BooleanField(default=True, verbose_name=b'aktif')),
            ],
        ),
    ]
