# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mentawai.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Nama')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Alam'), (2, b'Pantai'), (3, b'Panorama'), (4, b'Budaya'), (5, b'Diving'), (6, b'Snorkeling'), (7, b'Memancing'), (8, b'Hutan')], verbose_name=b'Tipe')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Description')),
                ('address', models.TextField(blank=True, null=True, verbose_name=b'Alamat')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, default=b'', upload_to=mentawai.core.utils.FilenameGenerator(prefix=b'tour-photo'))),
                ('is_active', models.BooleanField(default=True, verbose_name=b'aktif')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='locations.Location')),
            ],
        ),
    ]
