# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_tourist',
            field=models.BooleanField(default=False, verbose_name=b'Turis'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationaly',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Kebangsaan'),
        ),
        migrations.AddField(
            model_name='user',
            name='pasport_number',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Nomor Paspor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=b'Status aktif'),
        ),
    ]
